import{VERSION,BUILD_DATE,APP_NAME}from"./versions.js";
import{connectTC,getAPI,setStatus}from"./tc-api.js";
import{clearProfileSvg,renderProfileShell,renderGeometryDiagnostic}from"./svg-renderer.js";
import{GeometryRegistry}from"./geometry/geometry-registry.js";
const geometryRegistry=new GeometryRegistry();
const state={api:null,modelId:null,runtimeIds:[],selectedObject:null,alignmentPoints:[],alignmentLength:0,station:0,currentFrame:null,markerId:930170,markerIcon:null,markerSequence:0,sectionPlaneIds:[]};
const $=id=>document.getElementById(id),profileName=$("profileName"),profileId=$("profileId"),profileLength=$("profileLength"),stationInput=$("stationInput"),stationSlider=$("stationSlider"),stationLabel=$("stationLabel"),sectionWidthInput=$("sectionWidth"),profileSvg=$("profileSvg"),geometryFilesInput=$("geometryFiles"),geometrySourceList=$("geometrySourceList"),geometrySourceSummary=$("geometrySourceSummary"),markerUrl=new URL("../assets/station-marker.png",import.meta.url).href;
function log(title,value){console.log(`===== ${title} =====`);console.dir(value);}
function formatBytes(bytes){if(!bytes)return"0 B";const units=["B","KB","MB","GB"],i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),3);return`${(bytes/1024**i).toFixed(i?1:0)} ${units[i]}`;}
function renderSources(){const summary=geometryRegistry.getSummary();geometrySourceList.innerHTML="";for(const source of summary.sources){const item=document.createElement("div");item.className=`geometry-source geometry-source-${source.status}`;const main=document.createElement("div");main.className="geometry-source-main";main.textContent=`${source.fileName} (${source.type.toUpperCase()}, ${formatBytes(source.fileSize)})`;const details=document.createElement("div");details.className="geometry-source-details";details.textContent=source.status==="ready"?`${source.entityCount} entiteter, ${source.meshCount} mesh`:source.error||source.status;const remove=document.createElement("button");remove.className="geometry-source-remove";remove.textContent="Fjern";remove.onclick=()=>{geometryRegistry.remove(source.id);renderSources();};item.append(main,details,remove);geometrySourceList.appendChild(item);}geometrySourceSummary.textContent=summary.sourceCount?`${summary.sourceCount} filer: ${summary.ifcCount} IFC + ${summary.trbCount} TRB, ${formatBytes(summary.totalBytes)}`:"Ingen geometrifiler valgt";}
async function loadFiles(event){const files=event.target.files;if(!files?.length)return;setStatus(`Åpner ${files.length} geometrifiler...`);const results=await geometryRegistry.addFiles(files,progress=>{setStatus(`${progress.phase}: ${progress.file.name}`);renderSources();});const summary=geometryRegistry.getSummary();log("GEOMETRIKILDER",summary);setStatus(`${summary.readyCount} kilder klare (${summary.ifcCount} IFC + ${summary.trbCount} TRB)`);event.target.value="";}
function normalize(v){const n=Math.hypot(v.x,v.y,v.z);return n?{x:v.x/n,y:v.y/n,z:v.z/n}:{x:0,y:0,z:0};}
function stationValue(object){for(const set of object.properties||[]){if(set.name!=="Pset_Stationing")continue;const item=(set.properties||[]).find(p=>p.name==="Station"),value=Number(item?.value);if(Number.isFinite(value))return value/1000;}const fallback=Number(object.product?.name);return Number.isFinite(fallback)?fallback:null;}
function makePoints(properties){return(properties||[]).filter(o=>o.class==="IFCREFERENT"&&o.product?.objectType==="STATION"&&o.position).map(o=>({id:Number(o.id),station:stationValue(o),x:Number(o.position.x),y:Number(o.position.y),z:Number(o.position.z)})).filter(p=>Object.values(p).every(Number.isFinite)).sort((a,b)=>a.station-b.station);}
function interval(station){const p=state.alignmentPoints;if(p.length<2)return null;if(station<=p[0].station)return{start:p[0],end:p[1]};if(station>=p.at(-1).station)return{start:p.at(-2),end:p.at(-1)};for(let i=0;i<p.length-1;i++)if(station>=p[i].station&&station<=p[i+1].station)return{start:p[i],end:p[i+1]};return null;}
function evaluate(station){const i=interval(station);if(!i)return null;const d=i.end.station-i.start.station,r=d?Math.max(0,Math.min(1,(station-i.start.station)/d)):0,position={x:i.start.x+(i.end.x-i.start.x)*r,y:i.start.y+(i.end.y-i.start.y)*r,z:i.start.z+(i.end.z-i.start.z)*r},tangent=normalize({x:i.end.x-i.start.x,y:i.end.y-i.start.y,z:i.end.z-i.start.z}),h=normalize({x:tangent.x,y:tangent.y,z:0});return{station,position,tangent,horizontalTangent:h,horizontalNormal:{x:-h.y,y:h.x,z:0}};}
async function marker(frame){const api=getAPI();if(!frame||!api?.viewer?.addIcon)return;const seq=++state.markerSequence,icon={id:state.markerId,position:{x:frame.position.x,y:frame.position.y,z:frame.position.z+.2},iconPath:markerUrl,size:30};try{if(state.markerIcon)await api.viewer.removeIcon(state.markerIcon);if(seq!==state.markerSequence)return;await api.viewer.addIcon(icon);state.markerIcon=icon;}catch(error){console.error(error);}}
function updateStation(value){let station=Number(value),min=Number(stationSlider.min),max=Number(stationSlider.max);station=Math.max(min,Math.min(max,Number.isFinite(station)?station:min));state.station=station;stationInput.value=station.toFixed(3);stationSlider.value=station;stationLabel.textContent=station.toFixed(3);state.currentFrame=evaluate(station);marker(state.currentFrame);}
async function removePlane(){const api=getAPI();if(state.sectionPlaneIds.length&&api?.viewer?.removeSectionPlanes)try{await api.viewer.removeSectionPlanes(state.sectionPlaneIds);}catch(error){console.warn(error);}state.sectionPlaneIds=[];}
async function selectProfile(){try{const api=getAPI(),selection=await api.viewer.getSelection();if(!selection?.length)throw new Error("Ingen objekter valgt");const{modelId,objectRuntimeIds=[]}=selection[0],properties=await api.viewer.getObjectProperties(modelId,objectRuntimeIds),selected=properties[0];if(String(selected?.class).toUpperCase()!=="IFCALIGNMENT")throw new Error("Valgt objekt er ikke IFCALIGNMENT");state.modelId=modelId;state.runtimeIds=[...objectRuntimeIds];state.selectedObject=selected;profileName.value=selected.product?.name||"Ukjent";profileId.textContent=objectRuntimeIds[0];const children=await api.viewer.getHierarchyChildren(modelId,objectRuntimeIds,undefined,true),ids=(children||[]).map(x=>Number(x.id)).filter(Number.isFinite),hierarchy=await api.viewer.getObjectProperties(modelId,ids);state.alignmentPoints=makePoints(hierarchy);if(state.alignmentPoints.length<2)throw new Error("Fant ikke nok stasjonsreferenter");const first=state.alignmentPoints[0].station,last=state.alignmentPoints.at(-1).station;state.alignmentLength=last-first;profileLength.textContent=state.alignmentLength.toFixed(3)+" m";stationSlider.min=first;stationSlider.max=last;stationInput.min=first;stationInput.max=last;updateStation(first);setStatus("Profil valgt");}catch(error){alert(error.message);setStatus("Feil ved profilvalg");}}
async function viewerDiagnostic(api,frame,width){const objects=await api.viewer.getObjects({}),flat=[];for(const model of objects||[])for(const object of model.objects||[])flat.push({modelId:model.modelId,id:Number(object.id)});let boxes=0,candidates=0;const groups=new Map();for(const object of flat){if(!groups.has(object.modelId))groups.set(object.modelId,[]);groups.get(object.modelId).push(object.id);}for(const[modelId,ids]of groups)for(let start=0;start<ids.length;start+=300){const result=await api.viewer.getObjectBoundingBoxes(modelId,ids.slice(start,start+300));boxes+=(result||[]).length;for(const item of result||[]){const box=item.boundingBox;if(!box)continue;const corners=[];for(const x of[box.min.x,box.max.x])for(const y of[box.min.y,box.max.y])for(const z of[box.min.z,box.max.z]){const dx=x-frame.position.x,dy=y-frame.position.y;corners.push({o:dx*frame.horizontalNormal.x+dy*frame.horizontalNormal.y,l:dx*frame.horizontalTangent.x+dy*frame.horizontalTangent.y,z});}const min=k=>Math.min(...corners.map(p=>p[k])),max=k=>Math.max(...corners.map(p=>p[k]));if(min("l")<=1&&max("l")>=-1&&min("o")<=width/2&&max("o")>=-width/2&&min("z")<=frame.position.z+12&&max("z")>=frame.position.z-8)candidates++;}}return{totalObjects:flat.length,boundingBoxes:boxes,candidateCount:candidates};}
async function generate(){if(!state.currentFrame)return alert("Velg profileringslinje først");const api=getAPI(),frame=state.currentFrame,width=Number(sectionWidthInput.value)||50;try{await removePlane();const planes=await api.viewer.addSectionPlane({positionX:frame.position.x*1000,positionY:frame.position.y*1000,positionZ:frame.position.z*1000,directionX:-frame.horizontalTangent.x,directionY:-frame.horizontalTangent.y,directionZ:0,controlsVisible:true});state.sectionPlaneIds=(planes||[]).map(p=>Number(p.id)).filter(Number.isFinite);renderProfileShell(profileSvg,{station:frame.station,alignmentName:state.selectedObject.product?.name,centerElevation:frame.position.z,sectionWidth:width,version:VERSION});const viewer=await viewerDiagnostic(api,frame,width),sources=geometryRegistry.getSummary(),diagnostic={...viewer,sourceCount:sources.sourceCount,ifcCount:sources.ifcCount,trbCount:sources.trbCount,totalSourceEntities:sources.totalEntities};renderGeometryDiagnostic(profileSvg,diagnostic);log("SAMLET GEOMETRIDIAGNOSE",{viewer,sources});setStatus(`Snitt ${frame.station.toFixed(3)} - ${viewer.candidateCount} viewer-kandidater, ${sources.sourceCount} filkilder`);}catch(error){console.error(error);alert(error.message);}}
function bind(){$("btnSelectProfile").onclick=selectProfile;$("btnGenerate").onclick=generate;$("minus10").onclick=()=>updateStation(state.station-10);$("minus1").onclick=()=>updateStation(state.station-1);$("plus1").onclick=()=>updateStation(state.station+1);$("plus10").onclick=()=>updateStation(state.station+10);stationSlider.oninput=e=>updateStation(e.target.value);stationInput.onchange=e=>updateStation(e.target.value);geometryFilesInput.onchange=loadFiles;$("btnClearGeometry").onclick=()=>{geometryRegistry.clear();renderSources();};renderSources();}
async function init(){$("versionInfo").textContent="v"+VERSION;$("buildInfo").textContent=BUILD_DATE;console.log(APP_NAME,VERSION);state.api=await connectTC();setStatus("Trimble API koblet");}
bind();init();
