import{VERSION,BUILD_DATE,APP_NAME}from"./versions.js";import{connectTC,getAPI,setStatus}from"./tc-api.js";import{GeometryRegistry}from"./geometry/geometry-registry.js";import{renderProfileShell,renderGeometryDiagnostic}from"./svg-renderer.js";
const R=new GeometryRegistry(),S={api:null,points:[],selected:null,station:0,frame:null,marker:null,planeIds:[]},$=id=>document.getElementById(id),markerUrl=new URL("../assets/station-marker.png",import.meta.url).href;
function log(n,v){console.log(`===== ${n} =====`);console.dir(v);}function typeLabel(s){return s.type.toUpperCase()+" · "+s.origin+" · "+s.status;}
function renderSources(){const box=$("geometrySourceList"),sum=R.summary();box.innerHTML="";for(const s of sum.sources){const row=document.createElement("div");row.className=`geometry-source geometry-source-${s.status}`;const a=document.createElement("div");a.className="geometry-source-main";a.textContent=s.name;const b=document.createElement("div");b.className="geometry-source-details";b.textContent=typeLabel(s)+(s.entityCount?` · ${s.entityCount} entiteter`:"");const x=document.createElement("button");x.textContent="Fjern";x.className="geometry-source-remove";x.onclick=()=>{R.remove(s.id);renderSources();};row.append(a,b,x);box.appendChild(row);}$("geometrySourceSummary").textContent=`${sum.sourceCount} kilder · ${sum.viewerCount} fra visning · ${sum.localCount} lokale · ${sum.ifcCount} IFC + ${sum.trbCount} TRB`;}
async function discoverModels(){const api=getAPI();setStatus("Henter aktive modeller...");try{const methods=["getModels","getModelFiles"];let models=[];for(const name of methods){if(typeof api.viewer?.[name]==="function"){models=await api.viewer[name]();if(Array.isArray(models))break;}}if(!Array.isArray(models))models=[];log("AKTIVE VIEWER-MODELLER",models);R.syncViewerModels(models);renderSources();setStatus(`${R.summary().viewerCount} aktive IFC/TRB-modeller funnet`);}catch(e){console.error(e);setStatus("Kunne ikke hente aktive modeller - bruk lokale filer");}}
async function localFiles(e){await R.addLocalFiles(e.target.files,()=>renderSources());renderSources();log("GEOMETRIKILDER",R.summary());e.target.value="";}
const norm=v=>{const n=Math.hypot(v.x,v.y,v.z);return n?{x:v.x/n,y:v.y/n,z:v.z/n}:{x:0,y:0,z:0};};function stationOf(o){for(const p of o.properties||[]){const v=(p.properties||[]).find(x=>x.name==="Station");if(p.name==="Pset_Stationing"&&Number.isFinite(+v?.value))return+v.value/1000;}return Number(o.product?.name);}
function evaluate(st){const p=S.points;if(p.length<2)return null;let a=p[0],b=p[1];for(let i=0;i<p.length-1;i++)if(st>=p[i].station&&st<=p[i+1].station){a=p[i];b=p[i+1];break;}if(st>=p.at(-1).station){a=p.at(-2);b=p.at(-1);}const r=Math.max(0,Math.min(1,(st-a.station)/(b.station-a.station))),pos={x:a.x+(b.x-a.x)*r,y:a.y+(b.y-a.y)*r,z:a.z+(b.z-a.z)*r},h=norm({x:b.x-a.x,y:b.y-a.y,z:0});return{station:st,position:pos,horizontalTangent:h,horizontalNormal:{x:-h.y,y:h.x,z:0}};}
async function mark(f){const api=getAPI();if(S.marker)try{await api.viewer.removeIcon(S.marker);}catch{}const icon={id:930170,position:{x:f.position.x,y:f.position.y,z:f.position.z+.2},iconPath:markerUrl,size:30};await api.viewer.addIcon(icon);S.marker=icon;}
function setStation(v){const slider=$("stationSlider"),st=Math.max(+slider.min,Math.min(+slider.max,+v));S.station=st;$("stationInput").value=st.toFixed(3);slider.value=st;$("stationLabel").textContent=st.toFixed(3);S.frame=evaluate(st);if(S.frame)mark(S.frame);}
async function selectProfile(){try{const api=getAPI(),sel=await api.viewer.getSelection(),m=sel?.[0];if(!m)throw Error("Ingen profileringslinje valgt");const obj=(await api.viewer.getObjectProperties(m.modelId,m.objectRuntimeIds))[0];if(String(obj.class).toUpperCase()!=="IFCALIGNMENT")throw Error("Valgt objekt er ikke IFCALIGNMENT");S.selected=obj;$("profileName").value=obj.product?.name||"Ukjent";$("profileId").textContent=m.objectRuntimeIds[0];const children=await api.viewer.getHierarchyChildren(m.modelId,m.objectRuntimeIds,undefined,true),props=await api.viewer.getObjectProperties(m.modelId,children.map(x=>+x.id));S.points=props.filter(o=>o.class==="IFCREFERENT"&&o.product?.objectType==="STATION").map(o=>({station:stationOf(o),x:+o.position.x,y:+o.position.y,z:+o.position.z})).filter(p=>Object.values(p).every(Number.isFinite)).sort((a,b)=>a.station-b.station);if(S.points.length<2)throw Error("For få stasjonsreferenter");const first=S.points[0].station,last=S.points.at(-1).station;$("profileLength").textContent=(last-first).toFixed(3)+" m";$("stationSlider").min=first;$("stationSlider").max=last;$("stationInput").min=first;$("stationInput").max=last;setStation(first);setStatus("Profil valgt");}catch(e){alert(e.message);}}
async function viewerCandidates(api,f,w){const models=await api.viewer.getObjects({});let total=0,candidates=0;for(const model of models){const ids=(model.objects||[]).map(o=>+o.id);total+=ids.length;for(let i=0;i<ids.length;i+=300){const boxes=await api.viewer.getObjectBoundingBoxes(model.modelId,ids.slice(i,i+300));for(const item of boxes||[]){const b=item.boundingBox;if(!b)continue;const vals=[];for(const x of[b.min.x,b.max.x])for(const y of[b.min.y,b.max.y])for(const z of[b.min.z,b.max.z]){const dx=x-f.position.x,dy=y-f.position.y;vals.push({o:dx*f.horizontalNormal.x+dy*f.horizontalNormal.y,l:dx*f.horizontalTangent.x+dy*f.horizontalTangent.y,z});}const mn=k=>Math.min(...vals.map(v=>v[k])),mx=k=>Math.max(...vals.map(v=>v[k]));if(mn("l")<=1&&mx("l")>=-1&&mn("o")<=w/2&&mx("o")>=-w/2&&mn("z")<=f.position.z+12&&mx("z")>=f.position.z-8)candidates++;}}}return{totalObjects:total,candidateCount:candidates};}
async function generate(){if(!S.frame)return alert("Velg profileringslinje først");const api=getAPI(),f=S.frame,w=+$("sectionWidth").value||50;try{if(S.planeIds.length)await api.viewer.removeSectionPlanes(S.planeIds);const p=await api.viewer.addSectionPlane({positionX:f.position.x*1000,positionY:f.position.y*1000,positionZ:f.position.z*1000,directionX:-f.horizontalTangent.x,directionY:-f.horizontalTangent.y,directionZ:0,controlsVisible:true});S.planeIds=(p||[]).map(x=>+x.id).filter(Number.isFinite);renderProfileShell($("profileSvg"),{station:f.station,alignmentName:S.selected.product?.name,centerElevation:f.position.z,sectionWidth:w,version:VERSION});const view=await viewerCandidates(api,f,w),sources=R.summary();renderGeometryDiagnostic($("profileSvg"),{...view,...sources});setStatus(`Snitt ${f.station.toFixed(3)} · ${sources.viewerCount} aktive modeller · ${view.candidateCount} kandidater`);}catch(e){console.error(e);alert(e.message);}}
function bind(){$("btnRefreshModels").onclick=discoverModels;$("geometryFiles").onchange=localFiles;$("btnClearLocal").onclick=()=>{R.clearLocal();renderSources();};$("btnSelectProfile").onclick=selectProfile;$("btnGenerate").onclick=generate;$("minus10").onclick=()=>setStation(S.station-10);$("minus1").onclick=()=>setStation(S.station-1);$("plus1").onclick=()=>setStation(S.station+1);$("plus10").onclick=()=>setStation(S.station+10);$("stationSlider").oninput=e=>setStation(e.target.value);$("stationInput").onchange=e=>setStation(e.target.value);}
async function init(){$("versionInfo").textContent="v"+VERSION;$("buildInfo").textContent=BUILD_DATE;bind();renderSources();S.api=await connectTC();setStatus("Trimble API koblet");await discoverModels();window.addEventListener("tc-workspace-event",e=>{if(/model|view/i.test(String(e.detail?.event)))discoverModels();});console.log(APP_NAME,VERSION);}
init();
