import { transformPoint } from "./mesh-normalizer.js";
export const SECTION_ENGINE_VERSION="0.6.6.2-ifc-calibration-trb-world";
const EPS=1e-7,locks=new Map(),ID={name:"XYZ",axes:[0,1,2],signs:[1,1,1]};
const MAPS=[["XYZ",[0,1,2],[1,1,1]],["X-Y-Z",[0,1,2],[1,-1,-1]],["-XY-Z",[0,1,2],[-1,1,-1]],["-X-YZ",[0,1,2],[-1,-1,1]],["XZY",[0,2,1],[1,1,-1]],["XZ-Y",[0,2,1],[1,-1,1]],["-XZY",[0,2,1],[-1,1,1]],["-XZ-Y",[0,2,1],[-1,-1,-1]],["YXZ",[1,0,2],[1,1,-1]],["YX-Z",[1,0,2],[1,-1,1]],["Y-XZ",[1,0,2],[-1,1,1]],["Y-X-Z",[1,0,2],[-1,-1,-1]],["YZX",[1,2,0],[1,1,1]],["YZ-X",[1,2,0],[1,-1,-1]],["-YZX",[1,2,0],[-1,1,-1]],["-YZ-X",[1,2,0],[-1,-1,1]],["ZXY",[2,0,1],[1,1,1]],["ZX-Y",[2,0,1],[1,-1,-1]],["Z-XY",[2,0,1],[-1,1,-1]],["Z-X-Y",[2,0,1],[-1,-1,1]],["ZYX",[2,1,0],[1,1,-1]],["ZY-X",[2,1,0],[1,-1,1]],["Z-YX",[2,1,0],[-1,1,1]],["Z-Y-X",[2,1,0],[-1,-1,-1]]].map(([name,axes,signs])=>({name,axes,signs}));
const median=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2};
const mapArray=(v,m)=>m.axes.map((a,i)=>v[a]*m.signs[i]);
const mapPoint=(p,l)=>{const q=mapArray([p.x,p.y,p.z],l.mapping);return{x:q[0]+l.translation.x,y:q[1]+l.translation.y,z:q[2]+l.translation.z}};
function meshBounds(meshes){const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];let n=0;for(const m of meshes)for(let i=0;i+2<m.positions.length;i+=3){const p=transformPoint(m.transform,m.positions[i],m.positions[i+1],m.positions[i+2]),v=[p.x,p.y,p.z];for(let a=0;a<3;a++){min[a]=Math.min(min[a],v[a]);max[a]=Math.max(max[a],v[a])}n++}return n?{center:min.map((v,i)=>(v+max[i])/2),size:min.map((v,i)=>max[i]-v)}:null}
function boxData(b){if(!b?.min||!b?.max)return null;const min=[+b.min.x,+b.min.y,+b.min.z],max=[+b.max.x,+b.max.y,+b.max.z];return{center:min.map((v,i)=>(v+max[i])/2),size:min.map((v,i)=>max[i]-v)}}
function calibrate(sourceId,meshes,c){const byGuid=new Map();for(const m of meshes){const k=String(m.globalId||"");if(!k)continue;if(!byGuid.has(k))byGuid.set(k,[]);byGuid.get(k).push(m)}const pairs=[];for(const p of c?.pairs||[]){const a=meshBounds(byGuid.get(String(p.globalId||""))||[]),b=boxData(p.viewerBox);if(a&&b)pairs.push({a,b})}if(pairs.length<2)return{lock:null,diag:{sourceId,status:"insufficient-pairs",pairCount:pairs.length,requiredPairCount:2}};const scored=MAPS.map(mapping=>{const rows=pairs.map(({a,b})=>{const mc=mapArray(a.center,mapping),ms=mapping.axes.map(i=>a.size[i]);return{mc,ms,b,t:b.center.map((v,i)=>v-mc[i])}}),t=[0,1,2].map(i=>median(rows.map(r=>r.t[i]))),res=rows.map(r=>Math.hypot(...r.mc.map((v,i)=>v+t[i]-r.b.center[i]))),size=rows.map(r=>r.ms.reduce((s,v,i)=>s+Math.abs(v-r.b.size[i])/Math.max(.05,Math.abs(r.b.size[i])),0)/3),rms=Math.sqrt(res.reduce((s,v)=>s+v*v,0)/res.length),mr=median(res),se=size.reduce((s,v)=>s+v,0)/size.length;return{mapping,translation:{x:t[0],y:t[1],z:t[2]},pairCount:pairs.length,centerRms:rms,meanRelativeSizeError:se,score:rms+mr+se*10}}).sort((a,b)=>a.score-b.score),best=scored[0],lock={sourceId,mapping:best.mapping,translation:best.translation,pairCount:best.pairCount,centerRms:best.centerRms,meanRelativeSizeError:best.meanRelativeSizeError};locks.set(sourceId,lock);return{lock,diag:{sourceId,status:"calibrated",selectedMapping:best.mapping.name,translation:best.translation,pairCount:best.pairCount,centerRms:best.centerRms,meanRelativeSizeError:best.meanRelativeSizeError,candidates:scored.slice(0,8).map(x=>({mapping:x.mapping.name,score:x.score}))}}}
const distance=(p,pl)=>(p.x-pl.origin.x)*pl.normal.x+(p.y-pl.origin.y)*pl.normal.y+(p.z-pl.origin.z)*pl.normal.z;
const interpolate=(a,b,da,db)=>{const d=da-db,t=Math.abs(d)<EPS?0:da/d;return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t}};
function triangleHit(a,b,c,pl){const p=[a,b,c],d=p.map(x=>distance(x,pl)),h=[];for(let i=0;i<3;i++){const j=(i+1)%3;if(Math.abs(d[i])<=EPS)h.push(p[i]);if((d[i]<-EPS&&d[j]>EPS)||(d[i]>EPS&&d[j]<-EPS))h.push(interpolate(p[i],p[j],d[i],d[j]))}const u=[];for(const x of h)if(!u.some(q=>Math.hypot(q.x-x.x,q.y-x.y,q.z-x.z)<EPS))u.push(x);return u.length>=2?[u[0],u[1]]:null}
const profile=(p,f)=>{const dx=p.x-f.position.x,dy=p.y-f.position.y;return{offset:-(dx*f.horizontalNormal.x+dy*f.horizontalNormal.y),elevation:p.z}};
function intersectModel(meshes,frame,opt,lock){const half=(opt.sectionWidth||50)/2,minLen=opt.minimumSegmentLength||.001,plane={origin:frame.position,normal:frame.horizontalTangent},segments=[];let trianglesTested=0,invalidTriangles=0,minDistance=Infinity;for(const m of meshes){if(!m.positions||!m.indices||m.indices.length<3)continue;for(let i=0;i+2<m.indices.length;i+=3){trianglesTested++;const points=[m.indices[i],m.indices[i+1],m.indices[i+2]].map(ix=>{const o=Number(ix)*3;if(o+2>=m.positions.length)return null;return mapPoint(transformPoint(m.transform,m.positions[o],m.positions[o+1],m.positions[o+2]),lock)});if(points.some(p=>!p||![p.x,p.y,p.z].every(Number.isFinite))){invalidTriangles++;continue}for(const p of points)minDistance=Math.min(minDistance,Math.abs(distance(p,plane)));const hit=triangleHit(...points,plane);if(!hit)continue;const start=profile(hit[0],frame),end=profile(hit[1],frame);if(Math.abs(start.offset)>half&&Math.abs(end.offset)>half)continue;if(Math.hypot(end.offset-start.offset,end.elevation-start.elevation)<minLen)continue;segments.push({sourceId:m.sourceId,sourceType:m.sourceType||"ifc",entityId:m.entityId,globalId:m.globalId,className:m.className,name:m.name,color:m.color,start,end})}}return{segments,trianglesTested,invalidTriangles,minimumAbsolutePlaneDistance:Number.isFinite(minDistance)?minDistance:null,objectsDrawn:new Set(segments.map(s=>`${s.sourceId}:${s.entityId}`)).size}}
function profileDiagnostic(segments,width){if(!segments.length)return{classification:"ingen-geometri",confidence:1,metrics:{}};const offsets=[],elevations=[],objects=new Set();for(const s of segments){offsets.push(s.start.offset,s.end.offset);elevations.push(s.start.elevation,s.end.elevation);objects.add(`${s.sourceId}:${s.entityId}`)}const horizontalSpan=Math.max(...offsets)-Math.min(...offsets),verticalSpan=Math.max(...elevations)-Math.min(...elevations),bilateral=Math.min(...offsets)<-.25&&Math.max(...offsets)>.25;return{classification:bilateral&&objects.size>=3?"sannsynlig-tverrprofil":"uavklart",confidence:bilateral?.8:.4,metrics:{segmentCount:segments.length,objectCount:objects.size,horizontalSpan,verticalSpan,widthOccupancy:horizontalSpan/Math.max(1,width||50),bilateral}}}
export function clearCalibrationLocks(sourceId=null){if(sourceId===null)locks.clear();else locks.delete(String(sourceId))}
export function intersectMeshes(meshes,frame,options={}){const groups=new Map(),calibrations=new Map((options.calibrations||[]).map(x=>[String(x.sourceId),x]));for(const m of meshes||[]){const id=String(m.sourceId||"ukjent-modell");if(!groups.has(id))groups.set(id,[]);groups.get(id).push(m)}const segments=[],models=[],sourceDiagnostics={},bySourceType={ifc:{meshes:0,trianglesTested:0,segments:0},trb:{meshes:0,trianglesTested:0,segments:0}};let trianglesTested=0,firstMapping=null;for(const[sourceId,sourceMeshes]of groups){const type=sourceMeshes.some(m=>m.sourceType==="trb")?"trb":"ifc";let lock,diag,created=false;if(type==="trb"){lock={mapping:ID,translation:{x:0,y:0,z:0}};diag={sourceId,sourceType:type,status:"world-coordinates",selectedMapping:"XYZ",translation:lock.translation,pairCount:0}}else{lock=locks.get(sourceId);if(lock)diag={sourceId,sourceType:type,status:"reused",selectedMapping:lock.mapping.name,translation:lock.translation,pairCount:lock.pairCount,centerRms:lock.centerRms};else{const c=calibrate(sourceId,sourceMeshes,calibrations.get(sourceId));lock=c.lock;diag=c.diag;created=!!lock}}if(!lock){models.push(diag);sourceDiagnostics[sourceId]={sourceType:type,meshCount:sourceMeshes.length,trianglesTested:0,segmentCount:0,status:diag.status};continue}const r=intersectModel(sourceMeshes,frame,options,lock);segments.push(...r.segments);trianglesTested+=r.trianglesTested;if(!firstMapping&&type==="ifc")firstMapping=lock.mapping.name;const d={sourceType:type,meshCount:sourceMeshes.length,trianglesTested:r.trianglesTested,segmentCount:r.segments.length,objectsDrawn:r.objectsDrawn,invalidTriangles:r.invalidTriangles};sourceDiagnostics[sourceId]=d;bySourceType[type].meshes+=d.meshCount;bySourceType[type].trianglesTested+=d.trianglesTested;bySourceType[type].segments+=d.segmentCount;models.push({...diag,lockCreated:created,currentStation:frame.station,meshCount:d.meshCount,trianglesTested:d.trianglesTested,segmentCount:d.segmentCount,objectsDrawn:d.objectsDrawn,minimumAbsolutePlaneDistance:r.minimumAbsolutePlaneDistance})}const calibrationDiagnostic={lockCount:locks.size,models,rule:"IFC kalibreres mot Viewer-bokser. TRB brukes direkte i validerte verdenskoordinater."},result={segments,trianglesTested,meshesProcessed:meshes.length,objectsDrawn:new Set(segments.map(s=>`${s.sourceId}:${s.entityId}`)).size,selectedAxisMapping:firstMapping,profileTypeDiagnostic:profileDiagnostic(segments,options.sectionWidth||50),calibrationDiagnostic,sourceDiagnostics,bySourceType,sectionEngineVersion:SECTION_ENGINE_VERSION};console.log("===== VIEWER-IFC-KALIBRERING OG TRB-VERDENSKOORDINATER =====");console.dir(calibrationDiagnostic);window.__crossSectionSectionEngineResult=result;return result}
