import { transformPoint } from "./mesh-normalizer.js";
export const SECTION_ENGINE_VERSION="0.6.6.1-source-diagnostics";
const EPSILON=1e-7;
function distanceToPlane(p,plane){return(p.x-plane.origin.x)*plane.normal.x+(p.y-plane.origin.y)*plane.normal.y+(p.z-plane.origin.z)*plane.normal.z}
function interpolate(a,b,da,db){const d=da-db,t=Math.abs(d)<EPSILON?0:da/d;return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t}}
function triangleIntersection(a,b,c,plane){const points=[a,b,c],distances=points.map(p=>distanceToPlane(p,plane)),hits=[];for(let e=0;e<3;e++){const n=(e+1)%3,d1=distances[e],d2=distances[n];if(Math.abs(d1)<=EPSILON)hits.push(points[e]);if((d1<-EPSILON&&d2>EPSILON)||(d1>EPSILON&&d2<-EPSILON))hits.push(interpolate(points[e],points[n],d1,d2))}const unique=[];for(const p of hits)if(!unique.some(q=>Math.abs(q.x-p.x)<EPSILON&&Math.abs(q.y-p.y)<EPSILON&&Math.abs(q.z-p.z)<EPSILON))unique.push(p);return unique.length>=2?[unique[0],unique[1]]:null}
function toProfilePoint(p,frame){const dx=p.x-frame.position.x,dy=p.y-frame.position.y;return{offset:dx*frame.horizontalNormal.x+dy*frame.horizontalNormal.y,elevation:p.z}}
export function intersectMeshes(meshes,frame,options={}){const halfWidth=(options.sectionWidth||50)/2,minimumLength=options.minimumSegmentLength||0.001,plane={origin:frame.position,normal:frame.horizontalTangent},segments=[];let trianglesTested=0,skippedMeshes=0,invalidTriangles=0;const bySourceType={};for(const mesh of meshes){const positions=mesh?.positions,indices=mesh?.indices,transform=mesh?.transform,type=String(mesh?.sourceType||"unknown");const stats=bySourceType[type]||(bySourceType[type]={meshes:0,skippedMeshes:0,trianglesTested:0,segments:0,invalidTriangles:0});stats.meshes++;if(!positions||!indices||indices.length<3){skippedMeshes++;stats.skippedMeshes++;continue}for(let i=0;i+2<indices.length;i+=3){trianglesTested++;stats.trianglesTested++;const ia=Number(indices[i])*3,ib=Number(indices[i+1])*3,ic=Number(indices[i+2])*3;if(ic+2>=positions.length||![positions[ia],positions[ia+1],positions[ia+2],positions[ib],positions[ib+1],positions[ib+2],positions[ic],positions[ic+1],positions[ic+2]].every(Number.isFinite)){invalidTriangles++;stats.invalidTriangles++;continue}const a=transformPoint(transform,positions[ia],positions[ia+1],positions[ia+2]),b=transformPoint(transform,positions[ib],positions[ib+1],positions[ib+2]),c=transformPoint(transform,positions[ic],positions[ic+1],positions[ic+2]),hit=triangleIntersection(a,b,c,plane);if(!hit)continue;const start=toProfilePoint(hit[0],frame),end=toProfilePoint(hit[1],frame);if(Math.abs(start.offset)>halfWidth&&Math.abs(end.offset)>halfWidth)continue;if(Math.hypot(end.offset-start.offset,end.elevation-start.elevation)<minimumLength)continue;segments.push({sourceId:mesh.sourceId,sourceType:type,entityId:mesh.entityId,globalId:mesh.globalId,className:mesh.className,name:mesh.name,color:mesh.color,start,end});stats.segments++}}
const result={segments,trianglesTested,meshesProcessed:meshes.length,objectsDrawn:new Set(segments.map(s=>`${s.sourceId}:${s.entityId}`)).size,skippedMeshes,invalidTriangles,bySourceType,sectionEngineVersion:SECTION_ENGINE_VERSION};window.__crossSectionSectionEngineResult=result;return result}
